/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyIcons';

  static const IconData users_outline =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData hand_grab_o =
      const IconData(0xf255, fontFamily: _kFontFam);
  static const IconData hand_paper_o =
      const IconData(0xf256, fontFamily: _kFontFam);
  static const IconData hand_peace_o =
      const IconData(0xf25b, fontFamily: _kFontFam);
}
